-- migrate:up


CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    street TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    municipality TEXT NOT NULL
);

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id INTEGER NOT NULL
        REFERENCES customers(id),

    date DATE NOT NULL,

    task TEXT NOT NULL
        CHECK (task IN ('cleaning', 'repair', 'inspection')),

    location TEXT,
    description TEXT,

    status TEXT NOT NULL
        CHECK (status IN ('open', 'in progress', 'done'))
);
-- migrate:down

DROP TABLE projects;
DROP TABLE customers;


